In [2]:
import pandas as pd

In [3]:
df = pd.DataFrame ({'col1' : [1,2,3,4,5],
'col2' : [23,24,25,25,27],
'col3' : "Madhu chandra Gamidi Data Engineer".split()
}) 

In [4]:
df

col1  col2      col3
0     1    23     Madhu
1     2    24   chandra
2     3    25    Gamidi
3     4    25      Data
4     5    27  Engineer

In [6]:
df['col4'] = df['col1']**2

In [7]:
df

col1  col2      col3  col4
0     1    23     Madhu     1
1     2    24   chandra     4
2     3    25    Gamidi     9
3     4    25      Data    16
4     5    27  Engineer    25

In [8]:
df['col5'] = df['col3'].str[0] # first character from col3

In [9]:
df

col1  col2      col3  col4 col5
0     1    23     Madhu     1    M
1     2    24   chandra     4    c
2     3    25    Gamidi     9    G
3     4    25      Data    16    D
4     5    27  Engineer    25    E

In [10]:
def condition(a):
    if (a == 'M'):
        return 'M'
    else:
        return 'Z'

In [15]:
df['col6'] = df['col5'].apply(condition)  # apply will allow you to pass your own function

In [20]:
df.drop('col4_4', axis=1, inplace = True) # axis = 1 will select columns and inplace = True permanently removes from the dataframe

In [21]:
df

col1  col2      col3  col4 col5 col6
0     1    23     Madhu     1    M    M
1     2    24   chandra     4    c    Z
2     3    25    Gamidi     9    G    Z
3     4    25      Data    16    D    Z
4     5    27  Engineer    25    E    Z

In [23]:
df['col_6'] = df['col5'].apply(lambda a : 'M' if a == 'M' else 'Z') # can implement a lambda function as well

In [24]:
df

col1  col2      col3  col4 col5 col6 col_6
0     1    23     Madhu     1    M    M     M
1     2    24   chandra     4    c    Z     Z
2     3    25    Gamidi     9    G    Z     Z
3     4    25      Data    16    D    Z     Z
4     5    27  Engineer    25    E    Z     Z

In [26]:
df['col7'] = df['col3'].apply(len)

df

col1  col2      col3  col4 col5 col6 col_6  col7
0     1    23     Madhu     1    M    M     M     5
1     2    24   chandra     4    c    Z     Z     7
2     3    25    Gamidi     9    G    Z     Z     6
3     4    25      Data    16    D    Z     Z     4
4     5    27  Engineer    25    E    Z     Z     8

In [27]:
import math

In [29]:
df['col8'] = df['col2'].apply(math.log)

df

col1  col2      col3  col4 col5 col6 col_6  col7      col8
0     1    23     Madhu     1    M    M     M     5  3.135494
1     2    24   chandra     4    c    Z     Z     7  3.178054
2     3    25    Gamidi     9    G    Z     Z     6  3.218876
3     4    25      Data    16    D    Z     Z     4  3.218876
4     5    27  Engineer    25    E    Z     Z     8  3.295837

In [30]:
import numpy as np

In [31]:
l = ['Madhu',1,2,3,4]

type(l)

list

In [33]:
type(np.array(l))

numpy.ndarray

In [37]:
np.array([3,4,5,6,7,8.0])

array([3., 4., 5., 6., 7., 8.])

In [40]:
a = np.array([[1,2], [3,4]])

a

array([[1, 2],
       [3, 4]])

In [41]:
a[0][1]

2

In [42]:
a2 = np.array([1,2,3,4], ndmin= 4)

In [47]:
a2[0][0][0][0]

1

In [48]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [49]:
np.asarray([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [51]:
np.asanyarray([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [52]:
np.mat([1,2,3,4,5]) # minimum 2-dimensional

matrix([[1, 2, 3, 4, 5]])

In [57]:
np.fromfunction(lambda x,y : x==y ,(4,4)) # index of (0,0) (1,1) (2,2) (3,3) are the ones matching which returned as True

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [58]:
np.fromfunction(lambda x,y : x*y ,(4,4), dtype=int)

array([[0, 0, 0, 0],
       [0, 1, 2, 3],
       [0, 2, 4, 6],
       [0, 3, 6, 9]])

In [59]:
np.mat(np.fromfunction(lambda x,y : x*y ,(4,4), dtype=int))

matrix([[0, 0, 0, 0],
        [0, 1, 2, 3],
        [0, 2, 4, 6],
        [0, 3, 6, 9]])

In [60]:
np.fromfunction(lambda x,y,z : x*y*z ,(4,3,2), dtype=int)

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 1],
        [0, 2]],

       [[0, 0],
        [0, 2],
        [0, 4]],

       [[0, 0],
        [0, 3],
        [0, 6]]])